### ISSUE TITLE
Profanity Filter is not working

### ISSUE THREAD

**Issue by SaiKishore2** [jwils0n/profanity-filter#7]
Is it belongs to third party?  For me it is showing error  filter is not defined.

**Comment by jwils0n** [comment]
Can you please provide an example of how you're trying to use it?

**Comment by kashifeqbal** [comment]
If you are using in Node, you have to install using npm
You need to add your own dictionary of words
```
var filter = require('profanityfilter');
var wordList = require('profanity_filter.json'); \\ contains your dictionary
filter.seed(wordList);
filter.clean('your paragrapgh');
```
